"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ru' | 'kz' | 'en';

const translations = {
  ru: {
    nav: {
      home: 'Главная',
      map: 'Карта',
      history: 'История',
      support: 'Поддержка',
      login: 'Вход',
      register: 'Регистрация',
      logout: 'Выйти',
      profile: 'Профиль',
      notifications: 'Уведомления',
      myRequests: 'Мои заявки',
      dashboard: 'Кабинет',
    },
    home: {
      heroTitle1: 'Сообщайте о проблемах',
      heroTitle2: '—Улучшайте ',
      heroCity: 'Павлодар',
      aiTasks: 'AI-задачи',
      mainCta: 'Фотографируйте, описывайте и отправляйте',
      mainCtaSub: 'а наши службы всё исправят',
      submitRequest: 'Подать заявку',
      howItWorks: 'Как это работает?',
      step1: 'Сделайте фото',
      step1sub: 'проблемы',
      step2: 'Добавьте описание',
      step2sub: 'и адрес',
      step3: 'Мы поможем вам!',
      step3sub: 'AI назначит задачу',
      mapPreview: 'Карта проблем',
      mapPreviewSub: 'Смотрите активные заявки по городу в реальном времени',
      categoriesTitle: 'С чем мы поможем?',
      categoriesSub: 'Выберите категорию проблемы и сообщите о ней. Наш AI автоматически назначит подходящего специалиста.',
      ctaTitle: 'Готовы сделать город лучше?',
      ctaSub: 'Присоединяйтесь к тысячам граждан, которые уже помогают улучшать Павлодар',
      viewMap: 'Смотреть карту',
    },
    categories: {
      electricity: 'Электричество',
      water: 'Водопровод',
      roads: 'Дороги',
      garbage: 'Мусор',
      cleaning: 'Уборка',
      landscaping: 'Благоустройство',
    },
    map: {
      title: 'Карта проблем города',
      activeProblems: 'Активные проблемы',
      details: 'Детали заявки',
      category: 'Категория',
      description: 'Описание',
      address: 'Адрес',
      status: 'Статус',
      priority: 'Приоритет',
      coordinates: 'Координаты',
      tryAgain: 'Попробовать снова',
      noActiveRequests: 'Нет активных заявок',
      loading: 'Загрузка...',
    },
    request: {
      title: 'Создать заявку',
      selectCategory: 'Выберите категорию',
      section: 'Секция',
      problemCategory: 'Категория проблемы',
      descriptionAndPhoto: 'Описание и фото',
      addressAndLocation: 'Адрес и местоположение',
      addressInput: 'Ввод адреса',
      mapSelect: 'Карта',
      startTypingAddress: 'Начните вводить адрес...',
      myLocation: 'Мое местоположение',
      determining: 'Определяем...',
      selectOnMap: 'или выбрать на карте',
      clickOnMap: 'Кликните на карту для выбора места',
      describeProblem: 'Опишите проблему',
      descriptionPlaceholder: 'Опишите проблему подробнее...',
      attachPhoto: 'Прикрепите фото',
      clickToUpload: 'Нажмите для загрузки',
      back: 'Назад',
      next: 'Далее',
      submit: 'Отправить',
    },
    history: {
      title: 'История заявок',
      noRequests: 'У вас пока нет заявок',
      createFirst: 'Создать первую заявку',
      aiRecommendation: 'Рекомендация ИИ',
      closureReason: 'Причина закрытия',
      afterPhoto: 'Фото после выполнения',
    },
    status: {
      pending: 'Ожидает',
      assigned: 'Назначена',
      in_progress: 'В работе',
      completed: 'Завершена',
      closed: 'Закрыта',
      rejected: 'Отклонена',
    },
    priority: {
      low: 'Низкий',
      medium: 'Средний',
      high: 'Высокий',
    },
    auth: {
      loginTitle: 'Вход',
      loginSubtitle: 'Войдите в свой аккаунт',
      registerTitle: 'Регистрация',
      registerSubtitle: 'Создайте аккаунт гражданина',
      username: 'Логин (username)',
      usernamePlaceholder: 'Введите логин',
      password: 'Пароль',
      passwordPlaceholder: 'Минимум 6 символов',
      confirmPassword: 'Подтвердите пароль',
      email: 'Email',
      firstName: 'Имя',
      lastName: 'Фамилия',
      forgotPassword: 'Забыли пароль?',
      noAccount: 'Нет аккаунта?',
      haveAccount: 'Уже есть аккаунт?',
      loginButton: 'Войти',
      registerButton: 'Зарегистрироваться',
      next: 'Далее',
      back: 'Назад',
      registrationSuccess: 'Регистрация успешна! Теперь вы можете войти.',
    },
    footer: {
      slogan: 'Делаем город лучше вместе',
      navigation: 'Навигация',
      services: 'Услуги',
      contacts: 'Контакты',
      madeIn: 'Сделано в Казахстане',
      allRights: 'Все права защищены',
    },
    admin: {
      title: 'Панель администратора ЖКХ',
      overview: 'Обзор',
      users: 'Пользователи',
      employees: 'Сотрудники',
      requests: 'Заявки',
      totalRequests: 'Всего заявок',
      pendingRequests: 'Ожидающие',
      inProgress: 'В работе',
      completed: 'Выполнено',
      assignEmployee: 'Назначить',
      addEmployee: 'Добавить сотрудника',
      selectCitizen: 'Выберите жителя',
      makeEmployee: 'Сделать сотрудником',
      role: 'Роль',
      citizen: 'Житель',
      employee: 'Сотрудник',
      admin: 'Администратор',
    },
    worker: {
      title: 'Панель работника',
      myTasks: 'Мои задачи',
      assigned: 'Назначено',
      inProgress: 'В работе',
      completed: 'Выполнено',
      start: 'Начать',
      finish: 'Завершить',
      noTasks: 'Нет назначенных задач',
      viewOnMap: 'Посмотреть на карте',
    },
    common: {
      loading: 'Загрузка...',
      error: 'Ошибка',
      tryAgain: 'Попробовать снова',
      cancel: 'Отмена',
      save: 'Сохранить',
      delete: 'Удалить',
      edit: 'Редактировать',
      close: 'Закрыть',
      search: 'Поиск',
      filter: 'Фильтр',
      all: 'Все',
    },
  },
  kz: {
    nav: {
      home: 'Басты бет',
      map: 'Карта',
      history: 'Тарих',
      support: 'Қолдау',
      login: 'Кіру',
      register: 'Тіркелу',
      logout: 'Шығу',
      profile: 'Профиль',
      notifications: 'Хабарламалар',
      myRequests: 'Менің өтінімдерім',
      dashboard: 'Кабинет',
    },
    home: {
      heroTitle1: 'Мәселелер туралы хабарлаңыз',
      heroTitle2: '— ',
      heroCity: 'Павлодарды жақсартыңыз',
      aiTasks: 'AI-тапсырмалар',
      mainCta: 'Фото түсіріңіз, сипаттаңыз және жіберіңіз',
      mainCtaSub: 'ал біздің қызметтер барлығын түзетеді',
      submitRequest: 'Өтінім беру',
      howItWorks: 'Бұл қалай жұмыс істейді?',
      step1: 'Фото түсіріңіз',
      step1sub: 'мәселенің',
      step2: 'Сипаттама қосыңыз',
      step2sub: 'және мекенжайды',
      step3: 'Біз көмектесеміз!',
      step3sub: 'AI тапсырма тағайындайды',
      mapPreview: 'Мәселелер картасы',
      mapPreviewSub: 'Қала бойынша белсенді өтінімдерді нақты уақытта көріңіз',
      categoriesTitle: 'Біз немен көмектесеміз?',
      categoriesSub: 'Мәселе санатын таңдап, хабарлаңыз. Біздің AI автоматты түрде маманды тағайындайды.',
      ctaTitle: 'Қаланы жақсартуға дайынсыз ба?',
      ctaSub: 'Павлодарды жақсартуға көмектесетін мыңдаған азаматтарға қосылыңыз',
      viewMap: 'Картаны көру',
    },
    categories: {
      electricity: 'Электр',
      water: 'Су құбыры',
      roads: 'Жолдар',
      garbage: 'Қоқыс',
      cleaning: 'Тазалау',
      landscaping: 'Абаттандыру',
    },
    map: {
      title: 'Қала мәселелерінің картасы',
      activeProblems: 'Белсенді мәселелер',
      details: 'Өтінім мәліметтері',
      category: 'Санат',
      description: 'Сипаттама',
      address: 'Мекенжай',
      status: 'Мәртебе',
      priority: 'Басымдық',
      coordinates: 'Координаталар',
      tryAgain: 'Қайтадан байқап көру',
      noActiveRequests: 'Белсенді өтінімдер жоқ',
      loading: 'Жүктелуде...',
    },
    request: {
      title: 'Өтінім жасау',
      selectCategory: 'Санатты таңдаңыз',
      section: 'Бөлім',
      problemCategory: 'Мәселе санаты',
      descriptionAndPhoto: 'Сипаттама және фото',
      addressAndLocation: 'Мекенжай және орналасу',
      addressInput: 'Мекенжайды енгізу',
      mapSelect: 'Карта',
      startTypingAddress: 'Мекенжайды енгізуді бастаңыз...',
      myLocation: 'Менің орналасуым',
      determining: 'Анықталуда...',
      selectOnMap: 'немесе картадан таңдау',
      clickOnMap: 'Орынды таңдау үшін картаны басыңыз',
      describeProblem: 'Мәселені сипаттаңыз',
      descriptionPlaceholder: 'Мәселені толығырақ сипаттаңыз...',
      attachPhoto: 'Фото тіркеңіз',
      clickToUpload: 'Жүктеу үшін басыңыз',
      back: 'Артқа',
      next: 'Келесі',
      submit: 'Жіберу',
    },
    history: {
      title: 'Өтінімдер тарихы',
      noRequests: 'Сізде әлі өтінімдер жоқ',
      createFirst: 'Бірінші өтінімді жасау',
      aiRecommendation: 'AI ұсынысы',
      closureReason: 'Жабу себебі',
      afterPhoto: 'Орындалғаннан кейінгі фото',
    },
    status: {
      pending: 'Күтуде',
      assigned: 'Тағайындалды',
      in_progress: 'Орындалуда',
      completed: 'Аяқталды',
      closed: 'Жабылды',
      rejected: 'Қабылданбады',
    },
    priority: {
      low: 'Төмен',
      medium: 'Орташа',
      high: 'Жоғары',
    },
    auth: {
      loginTitle: 'Кіру',
      loginSubtitle: 'Аккаунтыңызға кіріңіз',
      registerTitle: 'Тіркелу',
      registerSubtitle: 'Азамат аккаунтын жасаңыз',
      username: 'Логин',
      usernamePlaceholder: 'Логинді енгізіңіз',
      password: 'Құпия сөз',
      passwordPlaceholder: 'Кемінде 6 таңба',
      confirmPassword: 'Құпия сөзді растаңыз',
      email: 'Email',
      firstName: 'Аты',
      lastName: 'Тегі',
      forgotPassword: 'Құпия сөзді ұмыттыңыз ба?',
      noAccount: 'Аккаунтыңыз жоқ па?',
      haveAccount: 'Аккаунтыңыз бар ма?',
      loginButton: 'Кіру',
      registerButton: 'Тіркелу',
      next: 'Келесі',
      back: 'Артқа',
      registrationSuccess: 'Тіркелу сәтті! Енді кіре аласыз.',
    },
    footer: {
      slogan: 'Қаланы бірге жақсартамыз',
      navigation: 'Навигация',
      services: 'Қызметтер',
      contacts: 'Байланыс',
      madeIn: 'Қазақстанда жасалған',
      allRights: 'Барлық құқықтар қорғалған',
    },
    admin: {
      title: 'ТКШ әкімші панелі',
      overview: 'Шолу',
      users: 'Пайдаланушылар',
      employees: 'Қызметкерлер',
      requests: 'Өтінімдер',
      totalRequests: 'Барлық өтінімдер',
      pendingRequests: 'Күтуде',
      inProgress: 'Орындалуда',
      completed: 'Аяқталды',
      assignEmployee: 'Тағайындау',
      addEmployee: 'Қызметкер қосу',
      selectCitizen: 'Тұрғынды таңдаңыз',
      makeEmployee: 'Қызметкер ету',
      role: 'Рөл',
      citizen: 'Тұрғын',
      employee: 'Қызметкер',
      admin: 'Әкімші',
    },
    worker: {
      title: 'Қызметкер панелі',
      myTasks: 'Менің тапсырмаларым',
      assigned: 'Тағайындалды',
      inProgress: 'Орындалуда',
      completed: 'Аяқталды',
      start: 'Бастау',
      finish: 'Аяқтау',
      noTasks: 'Тағайындалған тапсырмалар жоқ',
      viewOnMap: 'Картада көру',
    },
    common: {
      loading: 'Жүктелуде...',
      error: 'Қате',
      tryAgain: 'Қайтадан байқап көру',
      cancel: 'Болдырмау',
      save: 'Сақтау',
      delete: 'Жою',
      edit: 'Өңдеу',
      close: 'Жабу',
      search: 'Іздеу',
      filter: 'Сүзгі',
      all: 'Барлығы',
    },
  },
  en: {
    nav: {
      home: 'Home',
      map: 'Map',
      history: 'History',
      support: 'Support',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      profile: 'Profile',
      notifications: 'Notifications',
      myRequests: 'My Requests',
      dashboard: 'Dashboard',
    },
    home: {
      heroTitle1: 'Report Problems',
      heroTitle2: '—Improve ',
      heroCity: 'Pavlodar',
      aiTasks: 'AI Tasks',
      mainCta: 'Take a photo, describe and submit',
      mainCtaSub: 'and our services will fix everything',
      submitRequest: 'Submit Request',
      howItWorks: 'How it works?',
      step1: 'Take a photo',
      step1sub: 'of the problem',
      step2: 'Add description',
      step2sub: 'and address',
      step3: 'We will help!',
      step3sub: 'AI will assign a task',
      mapPreview: 'Problems Map',
      mapPreviewSub: 'View active requests across the city in real-time',
      categoriesTitle: 'What can we help with?',
      categoriesSub: 'Choose a problem category and report it. Our AI will automatically assign a suitable specialist.',
      ctaTitle: 'Ready to make the city better?',
      ctaSub: 'Join thousands of citizens who are already helping improve Pavlodar',
      viewMap: 'View Map',
    },
    categories: {
      electricity: 'Electricity',
      water: 'Water Supply',
      roads: 'Roads',
      garbage: 'Garbage',
      cleaning: 'Cleaning',
      landscaping: 'Landscaping',
    },
    map: {
      title: 'City Problems Map',
      activeProblems: 'Active Problems',
      details: 'Request Details',
      category: 'Category',
      description: 'Description',
      address: 'Address',
      status: 'Status',
      priority: 'Priority',
      coordinates: 'Coordinates',
      tryAgain: 'Try again',
      noActiveRequests: 'No active requests',
      loading: 'Loading...',
    },
    request: {
      title: 'Create Request',
      selectCategory: 'Select Category',
      section: 'Section',
      problemCategory: 'Problem Category',
      descriptionAndPhoto: 'Description and Photo',
      addressAndLocation: 'Address and Location',
      addressInput: 'Enter Address',
      mapSelect: 'Map',
      startTypingAddress: 'Start typing address...',
      myLocation: 'My Location',
      determining: 'Determining...',
      selectOnMap: 'or select on map',
      clickOnMap: 'Click on map to select location',
      describeProblem: 'Describe the problem',
      descriptionPlaceholder: 'Describe the problem in detail...',
      attachPhoto: 'Attach Photo',
      clickToUpload: 'Click to upload',
      back: 'Back',
      next: 'Next',
      submit: 'Submit',
    },
    history: {
      title: 'Request History',
      noRequests: 'You have no requests yet',
      createFirst: 'Create your first request',
      aiRecommendation: 'AI Recommendation',
      closureReason: 'Closure Reason',
      afterPhoto: 'Photo after completion',
    },
    status: {
      pending: 'Pending',
      assigned: 'Assigned',
      in_progress: 'In Progress',
      completed: 'Completed',
      closed: 'Closed',
      rejected: 'Rejected',
    },
    priority: {
      low: 'Low',
      medium: 'Medium',
      high: 'High',
    },
    auth: {
      loginTitle: 'Login',
      loginSubtitle: 'Sign in to your account',
      registerTitle: 'Register',
      registerSubtitle: 'Create a citizen account',
      username: 'Username',
      usernamePlaceholder: 'Enter username',
      password: 'Password',
      passwordPlaceholder: 'At least 6 characters',
      confirmPassword: 'Confirm Password',
      email: 'Email',
      firstName: 'First Name',
      lastName: 'Last Name',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      loginButton: 'Login',
      registerButton: 'Register',
      next: 'Next',
      back: 'Back',
      registrationSuccess: 'Registration successful! You can now log in.',
    },
    footer: {
      slogan: 'Making the city better together',
      navigation: 'Navigation',
      services: 'Services',
      contacts: 'Contacts',
      madeIn: 'Made in Kazakhstan',
      allRights: 'All rights reserved',
    },
    admin: {
      title: 'Housing Admin Panel',
      overview: 'Overview',
      users: 'Users',
      employees: 'Employees',
      requests: 'Requests',
      totalRequests: 'Total Requests',
      pendingRequests: 'Pending',
      inProgress: 'In Progress',
      completed: 'Completed',
      assignEmployee: 'Assign',
      addEmployee: 'Add Employee',
      selectCitizen: 'Select Citizen',
      makeEmployee: 'Make Employee',
      role: 'Role',
      citizen: 'Citizen',
      employee: 'Employee',
      admin: 'Administrator',
    },
    worker: {
      title: 'Worker Panel',
      myTasks: 'My Tasks',
      assigned: 'Assigned',
      inProgress: 'In Progress',
      completed: 'Completed',
      start: 'Start',
      finish: 'Finish',
      noTasks: 'No assigned tasks',
      viewOnMap: 'View on Map',
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      tryAgain: 'Try again',
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      search: 'Search',
      filter: 'Filter',
      all: 'All',
    },
  },
};

type Translations = typeof translations.ru;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ru');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['ru', 'kz', 'en'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = translations[language];

  if (!mounted) {
    return <>{children}</>;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    // Return default values if outside provider
    return {
      language: 'ru' as Language,
      setLanguage: () => {},
      t: translations.ru,
    };
  }
  return context;
}

export { translations };

